CRYPTO_COINS: tuple[tuple[str, str, str], ...] = (
    ("bitcoin", "BTC", "Bitcoin"),
    ("ethereum", "ETH", "Ethereum"),
    ("ripple", "XRP", "XRP"),
    ("tether", "USDT", "Tether"),
    ("binancecoin", "BNB", "BNB"),
    ("solana", "SOL", "Solana"),
    ("usd-coin", "USDC", "USDC"),
    ("tron", "TRX", "TRON"),
    ("dogecoin", "DOGE", "Dogecoin"),
    ("cardano", "ADA", "Cardano"),
    ("chainlink", "LINK", "Chainlink"),
    ("hyperliquid", "HYPE", "Hyperliquid"),
    ("stellar", "XLM", "Stellar"),
    ("sui", "SUI", "Sui"),
    ("ethena-usde", "USDE", "Ethena USDe"),
    ("bitcoin-cash", "BCH", "Bitcoin Cash"),
    ("hedera-hashgraph", "HBAR", "Hedera"),
    ("avalanche-2", "AVAX", "Avalanche"),
    ("leo-token", "LEO", "LEO Token"),
    ("litecoin", "LTC", "Litecoin"),
    ("the-open-network", "TON", "Toncoin"),
    ("shiba-inu", "SHIB", "Shiba Inu"),
    ("uniswap", "UNI", "Uniswap"),
    ("polkadot", "DOT", "Polkadot"),
    ("dai", "DAI", "Dai"),
    ("bitget-token", "BGB", "Bitget Token"),
    ("monero", "XMR", "Monero"),
    ("crypto-com-chain", "CRO", "Cronos"),
    ("aave", "AAVE", "Aave"),
    ("okb", "OKB", "OKB"),
    ("pepe", "PEPE", "Pepe"),
    ("mantle", "MNT", "Mantle"),
    ("ethena", "ENA", "Ethena"),
    ("bittensor", "TAO", "Bittensor"),
    ("ethereum-classic", "ETC", "Ethereum Classic"),
    ("near", "NEAR", "NEAR Protocol"),
    ("aptos", "APT", "Aptos"),
    ("ondo-finance", "ONDO", "Ondo"),
    ("pi-network", "PI", "Pi Network"),
    ("internet-computer", "ICP", "Internet Computer"),
    ("arbitrum", "ARB", "Arbitrum"),
    ("polygon-ecosystem-token", "POL", "POL (ex-MATIC)"),
    ("usd1-wlfi", "USD1", "USD1"),
    ("kaspa", "KAS", "Kaspa"),
    ("gatechain-token", "GT", "Gate"),
    ("algorand", "ALGO", "Algorand"),
    ("cosmos", "ATOM", "Cosmos Hub"),
    ("vechain", "VET", "VeChain"),
    ("pudgy-penguins", "PENGU", "Pudgy Penguins"),
    ("render-token", "RENDER", "Render"),
    ("worldcoin-wld", "WLD", "Worldcoin"),
    ("sei-network", "SEI", "Sei"),
    ("story-2", "IP", "Story"),
    ("bonk", "BONK", "Bonk"),
    ("official-trump", "TRUMP", "Official Trump"),
    ("flare-networks", "FLR", "Flare"),
    ("filecoin", "FIL", "Filecoin"),
    ("fetch-ai", "FET", "Artificial Superintelligence Alliance"),
    ("kucoin-shares", "KCS", "KuCoin"),
    ("jupiter-exchange-solana", "JUP", "Jupiter"),
    ("xdce-crowd-sale", "XDC", "XDC Network"),
    ("first-digital-usd", "FDUSD", "First Digital USD"),
    ("sky", "SKY", "Sky"),
    ("four", "FORM", "Four"),
    ("injective-protocol", "INJ", "Injective"),
    ("quant-network", "QNT", "Quant"),
    ("celestia", "TIA", "Celestia"),
    ("optimism", "OP", "Optimism"),
    ("paypal-usd", "PYUSD", "PayPal USD"),
    ("curve-dao-token", "CRV", "Curve DAO"),
    ("blockstack", "STX", "Stacks"),
    ("spx6900", "SPX", "SPX6900"),
    ("aerodrome-finance", "AERO", "Aerodrome Finance"),
    ("lido-dao", "LDO", "Lido DAO"),
    ("immutable-x", "IMX", "Immutable"),
    ("pump-fun", "PUMP", "Pump.fun"),
    ("floki", "FLOKI", "FLOKI"),
    ("pax-gold", "PAXG", "PAX Gold"),
    ("the-graph", "GRT", "The Graph"),
    ("sonic-3", "S", "Sonic"),
    ("conflux-token", "CFX", "Conflux"),
    ("pendle", "PENDLE", "Pendle"),
    ("pancakeswap-token", "CAKE", "PancakeSwap"),
    ("ethereum-name-service", "ENS", "Ethereum Name Service"),
    ("kaia", "KAIA", "Kaia"),
    ("fartcoin", "FARTCOIN", "Fartcoin"),
    ("raydium", "RAY", "Raydium"),
    ("tezos", "XTZ", "Tezos"),
    ("dogwifcoin", "WIF", "dogwifhat"),
    ("nexo", "NEXO", "NEXO"),
    ("tether-gold", "XAUT", "Tether Gold"),
    ("virtual-protocol", "VIRTUAL", "Virtuals Protocol"),
    ("vaulta", "A", "Vaulta"),
    ("theta-token", "THETA", "Theta Network"),
    ("iota", "IOTA", "IOTA"),
    ("morpho", "MORPHO", "Morpho"),
    ("jasmycoin", "JASMY", "JasmyCoin"),
    ("gala", "GALA", "GALA"),
    ("the-sandbox", "SAND", "The Sandbox"),
    ("newton-project", "AB", "AB"),
    ("pyth-network", "PYTH", "Pyth Network"),
    ("ripple-usd", "RLUSD", "Ripple USD"),
    ("zcash", "ZEC", "Zcash"),
    ("bittorrent", "BTT", "BitTorrent"),
    ("jito-governance-token", "JTO", "Jito"),
    ("flow", "FLOW", "Flow"),
    ("dexe", "DEXE", "DeXe"),
    ("walrus-2", "WAL", "Walrus"),
    ("decentraland", "MANA", "Decentraland"),
    ("build-on", "B", "BUILDon"),
    ("bitcoin-cash-sv", "BSV", "Bitcoin SV"),
    ("deep", "DEEP", "DeepBook"),
    ("ether-fi", "ETHFI", "Ether.fi"),
    ("true-usd", "TUSD", "TrueUSD"),
    ("starknet", "STRK", "Starknet"),
    ("dydx-chain", "DYDX", "dYdX"),
    ("helium", "HNT", "Helium"),
    ("syrup", "SYRUP", "Maple Finance"),
    ("based-brett", "BRETT", "Brett"),
    ("coredaoorg", "CORE", "Core"),
    ("neo", "NEO", "NEO"),
    ("usdd", "USDD", "USDD"),
    ("reserve-rights-token", "RSR", "Reserve Rights"),
    ("memecore", "M", "MemeCore"),
    ("apenft", "NFT", "AINFT"),
    ("sun-token", "SUN", "Sun Token"),
    ("zksync", "ZK", "ZKsync"),
    ("thorchain", "RUNE", "THORChain"),
    ("apecoin", "APE", "ApeCoin"),
    ("arweave", "AR", "Arweave"),
    ("chain-2", "XCN", "Onyxcoin"),
    ("aioz-network", "AIOZ", "AIOZ Network"),
    ("compound-governance-token", "COMP", "Compound"),
    ("elrond-erd-2", "EGLD", "MultiversX"),
    ("eigenlayer", "EIGEN", "EigenCloud (prev. EigenLayer)"),
    ("zebec-network", "ZBCN", "Zebec Network"),
    ("kava", "KAVA", "Kava"),
    ("mog-coin", "MOG", "Mog Coin"),
    ("ecash", "XEC", "eCash"),
    ("superfarm", "SUPER", "SuperVerse"),
    ("convex-finance", "CVX", "Convex Finance"),
    ("chiliz", "CHZ", "Chiliz"),
    ("axie-infinity", "AXS", "Axie Infinity"),
    ("aethir", "ATH", "Aethir"),
    ("wormhole", "W", "Wormhole"),
    ("wemix-token", "WEMIX", "WEMIX"),
    ("ronin", "RON", "Ronin"),
    ("beam-2", "BEAM", "Beam"),
    ("layerzero", "ZRO", "LayerZero"),
    ("1inch", "1INCH", "1INCH"),
    ("gnosis", "GNO", "Gnosis"),
    ("movement", "MOVE", "Movement"),
    ("just", "JST", "JUST"),
    ("snek", "SNEK", "Snek"),
    ("creditcoin-2", "CTC", "Creditcoin"),
    ("terra-luna", "LUNC", "Terra Luna Classic"),
    ("trust-wallet-token", "TWT", "Trust Wallet"),
    ("axelar", "AXL", "Axelar"),
    ("amp-token", "AMP", "Amp"),
    ("ftx-token", "FTT", "FTX Token"),
    ("akash-network", "AKT", "Akash Network"),
    ("toshi", "TOSHI", "Toshi"),
    ("decred", "DCR", "Decred"),
    ("zora", "ZORA", "Zora"),
    ("turbo", "TURBO", "Turbo"),
    ("dash", "DASH", "Dash"),
    ("livepeer", "LPT", "Livepeer"),
    ("berachain-bera", "BERA", "Berachain"),
    ("popcat", "POPCAT", "Popcat"),
    ("iotex", "IOTX", "IoTeX"),
    ("bio-protocol", "BIO", "Bio Protocol"),
    ("dog-go-to-the-moon-rune", "DOG", "Dog (Bitcoin)"),
    ("kaito", "KAITO", "KAITO"),
    ("safe", "SAFE", "Safe"),
    ("velo", "VELO", "Velo"),
    ("cat-in-a-dogs-world", "MEW", "cat in a dogs world"),
    ("mocaverse", "MOCA", "Moca Network"),
    ("yzy", "YZY", "YZY"),
    ("qtum", "QTUM", "Qtum"),
    ("mantra", "OM", "MANTRA"),
    ("kusama", "KSM", "Kusama"),
    ("theta-fuel", "TFUEL", "Theta Fuel"),
    ("frax", "FRAX", "Legacy Frax Dollar"),
    ("golem", "GLM", "Golem"),
    ("mx-token", "MX", "MX"),
    ("cheems-token", "CHEEMS", "Cheems Token"),
    ("euro-coin", "EURC", "EURC"),
    ("safepal", "SFP", "SafePal"),
    ("nervos-network", "CKB", "Nervos Network"),
    ("mina-protocol", "MINA", "Mina Protocol"),
    ("havven", "SNX", "Synthetix"),
    ("gas", "GAS", "Gas"),
    ("basic-attention-token", "BAT", "Basic Attention"),
    ("plume", "PLUME", "Plume"),
    ("useless-3", "USELESS", "Useless Coin"),
    ("zilliqa", "ZIL", "Zilliqa"),
    ("peanut-the-squirrel", "PNUT", "Peanut the Squirrel"),
    ("succinct", "PROVE", "Succinct"),
    ("skale", "SKL", "SKALE"),
    ("sushi", "SUSHI", "Sushi"),
    ("zero-gravity", "0G", "0G"),
    ("doublezero", "2Z", "DoubleZero"),
    ("the9bit", "9BIT", "The9bit"),
    ("a7a5", "A7A5", "A7A5"),
    ("abey", "ABEY", "Abey"),
    ("arcblock", "ABT", "Arcblock"),
    ("alchemy-pay", "ACH", "Alchemy Pay"),
    ("anemoy-tokenized-apollo-diversified-credit-fund", "ACRDX", "Anemoy Tokenized Apollo Diversified Credit Fund"),
    ("apollo-diversified-credit-securitize-fund", "ACRED", "Apollo Diversified Credit Securitize Fund"),
    ("acurast", "ACU", "Acurast"),
    ("across-protocol", "ACX", "Across Protocol"),
    ("advertise-coin", "ADCO", "Advertise Coin"),
    ("adi-token", "ADI", "ADI"),
    ("adshares", "ADS", "Adshares"),
    ("aergo", "AERGO", "Aergo [OLD]"),
    ("aevo-exchange", "AEVO", "Aevo"),
    ("agentfun-ai", "AGENTFUN", "AgentFun.AI"),
    ("kelp-gain", "AGETH", "Kelp Gain"),
    ("delysium", "AGI", "Delysium"),
    ("singularitynet", "AGIX", "SingularityNET"),
    ("adventure-gold", "AGLD", "Adventure Gold"),
    ("gensyn", "AI", "Gensyn"),
    ("ai-analysis-token", "AIAT", "AI Analysis Token"),
    ("ai-companions", "AIC", "AI Companions"),
    ("gaib-aid", "AID", "GAIB AID"),
    ("aintivirus", "AINTI", "AIntivirus"),
    ("olaxbt", "AIO", "OlaXBT"),
    ("okzoo", "AIOT", "OKZOO"),
    ("ai-powered-finance", "AIPF", "AI Powered Finance"),
    ("aixbt", "AIXBT", "aixbt"),
    ("alchemist-ai", "ALCH", "Alchemist AI"),
    ("aleo", "ALEO", "ALEO"),
    ("allora", "ALLO", "Allora"),
    ("altlayer", "ALT", "AltLayer"),
    ("america-party-5", "AMERICA", "America Party"),
    ("nirvana-ana-2", "ANA", "Nirvana ANA"),
    ("anime", "ANIME", "Animecoin"),
    ("ankr", "ANKR", "Ankr Network"),
    ("autonomi", "ANT", "Autonomi"),
    ("anvil", "ANVL", "Anvil"),
    ("ao-computer", "AO", "ao Computer"),
    ("apex-4", "AP3X", "APEX"),
    ("ape-and-pepe", "APEPE", "Ape and Pepe"),
    ("apes-2-2", "APES", "APES"),
    ("apex-token-2", "APEX", "APEX"),
    ("api3", "API3", "Api3"),
    ("apriori", "APR", "aPriori"),
    ("apertum", "APTM", "Apertum"),
    ("apxusd", "APXUSD", "apxUSD"),
    ("apyusd", "APYUSD", "apyUSD"),
    ("araracoin", "ARARA", "Araracoin"),
    ("ai-rig-complex", "ARC", "AI Rig Complex"),
    ("ardor", "ARDR", "Ardor"),
    ("ark", "ARK", "ARK"),
    ("arkham", "ARKM", "Arkham"),
    ("pirate-chain", "ARRR", "Pirate Chain"),
    ("asset", "ASSET", "REAL"),
    ("aster-2", "ASTER", "Aster"),
    ("asteroid-shiba", "ASTEROID", "Asteroid Shiba"),
    ("astar", "ASTR", "Astar"),
    ("apro", "AT", "Apro"),
    ("atomone", "ATONE", "AtomOne"),
    ("atoshi", "ATOS", "Atoshi"),
    ("auction", "AUCTION", "Bounce"),
    ("audius", "AUDIO", "Audius"),
    ("auki-labs", "AUKI", "Auki"),
    ("aurora-near", "AURORA", "Aurora"),
    ("agora-dollar", "AUSD", "AUSD"),
    ("alloy-tether", "AUSDT", "Alloy Tether"),
    ("concierge-io", "AVA", "AVA (Travala)"),
    ("avail", "AVAIL", "Avail"),
    ("altura-2", "AVLT", "Altura Vault Tokens"),
    ("avantis", "AVNT", "Avantis"),
    ("avant-usd", "AVUSD", "Avant USD"),
    ("stp-network", "AWE", "AWE Network"),
    ("aztec", "AZTEC", "Aztec"),
    ("bsquared-network", "B2", "BSquared Network"),
    ("bit2me", "B2M", "Bit2Me"),
    ("b3", "B3", "B3 (Base)"),
    ("babylon", "BABY", "Babylon"),
    ("baby-doge-coin", "BABYDOGE", "Baby Doge Coin"),
    ("comedian", "BAN", "Comedian"),
    ("banana-for-scale-2", "BANANAS31", "Banana For Scale"),
    ("band-protocol", "BAND", "Band"),
    ("lombard-protocol", "BARD", "Lombard"),
    ("bas", "BAS", "BNB Attestation Service"),
    ("basedhype", "BASEDHYPE", "BasedHype"),
    ("babyboomtoken", "BBT", "BabyBoomToken"),
    ("bc-token", "BC", "BCGame Coin"),
    ("blockchain-capital", "BCAP", "Blockchain Capital"),
    ("bitcastle-token", "BCE", "bitcastle Token"),
    ("bitchemical-token", "BCHEM", "Bitchemical Token"),
    ("backed-cspx-core-s-p-500", "BCSPX", "Backed CSPX Core S&P 500"),
    ("bitdca", "BDCA", "BitDCA"),
    ("bdtcoin", "BDTC", "BDTCOIN"),
    ("beldex", "BDX", "Beldex"),
    ("audiera", "BEAT", "Audiera"),
    ("bifrost", "BFC", "Bifrost"),
    ("bfusd", "BFUSD", "BFUSD"),
    ("bitget-wrapped-btc", "BGBTC", "Bitget Wrapped BTC"),
    ("backed-ib01-treasury-bond-0-1yr", "BIB01", "Backed IB01 $ Treasury Bond 0-1yr"),
    ("biconomy", "BICO", "Biconomy"),
    ("big-time", "BIGTIME", "Big Time"),
    ("billions-network", "BILL", "Billions Network"),
    ("bim-2", "BIM", "BIM"),
    ("moonbirds", "BIRB", "Moonbirds"),
    ("harrypotterobamasonic10in", "BITCOIN", "HarryPotterObamaSonic10Inu (ETH)"),
    ("blast", "BLAST", "Blast"),
    ("fluent-network", "BLEND", "Fluent"),
    ("blur", "BLUR", "Blur"),
    ("bitmart-token", "BMX", "BitMart"),
    ("bankercoin-2", "BNKR", "BankrCoin"),
    ("bancor", "BNT", "Bancor Network"),
    ("binaryx", "BNX", "BinaryX [OLD]"),
    ("bob-build-on-bitcoin", "BOB", "BOB (Build on Bitcoin)"),
    ("liquity-bold-2", "BOLD", "BOLD"),
    ("book-of-meme", "BOME", "BOOK OF MEME"),
    ("bora", "BORA", "BORA"),
    ("swissborg", "BORG", "SwissBorg"),
    ("botxcoin", "BOTX", "BOTXCOIN"),
    ("debox", "BOX", "DeBox"),
    ("backpack", "BP", "Backpack"),
    ("black-phoenix", "BPX", "Black Phoenix"),
    ("bedrock-token", "BR", "Bedrock"),
    ("brevis", "BREV", "Brevis"),
    ("brla-digital-brla", "BRLA", "BRLA Digital BRLA"),
    ("crown-brlv", "BRLV", "Crown BRLV"),
    ("brz", "BRZ", "Brazilian Digital"),
    ("block-street", "BSB", "Block Street"),
    ("btse-token", "BTSE", "BTSE Token"),
    ("bitway", "BTW", "Bitway"),
    ("bityuan", "BTY", "Bityuan"),
    ("bucket-protocol-buck-stablecoin", "BUCK", "Bucket Protocol BUCK Stablecoin"),
    ("blackrock-usd-institutional-digital-liquidity-fund", "BUIDL", "BlackRock USD Institutional Digital Liquidity Fund"),
    ("binance-usd", "BUSD", "BUSD"),
    ("coin98", "C98", "Coin98"),
    ("capx-ai", "CAPX", "Capx AI"),
    ("collector-crypt", "CARDS", "Collector Crypt"),
    ("carv", "CARV", "CARV"),
    ("cash-4", "CASH", "CASH"),
    ("catizen", "CATI", "Catizen"),
    ("a-hunters-dream", "CAW", "A Hunters Dream"),
    ("cobak-token", "CBK", "Cobak"),
    ("canton-network", "CC", "Canton"),
    ("concordium", "CCD", "Concordium"),
    ("celo", "CELO", "Celo"),
    ("coinex-token", "CET", "CoinEx"),
    ("cetus-protocol", "CETUS", "Cetus Protocol"),
    ("centrifuge-2", "CFG", "Centrifuge"),
    ("chaingpt", "CGPT", "ChainGPT"),
    ("cygnus-finance-global-usd", "CGUSD", "Cygnus Finance Global USD"),
    ("checkmate-2", "CHECK", "Checkmate"),
    ("chex-token", "CHEX", "Chintai"),
    ("chip-2", "CHIP", "USD.AI"),
    ("chromaway", "CHR", "Chromia"),
    ("tokenbot-2", "CLANKER", "tokenbot"),
    ("chainopera-ai", "COAI", "ChainOpera AI"),
    ("chinese-oil-asset-reserve", "COAR", "Chinese Oil Asset Reserve"),
    ("coindepo", "COINDEPO", "COINDEPO"),
    ("collect-on-fanable", "COLLECT", "Collect on Fanable"),
    ("corn-3", "CORN", "Corn"),
    ("coti", "COTI", "COTI"),
    ("cow-protocol", "COW", "CoW Protocol"),
    ("clearpool", "CPOOL", "Clearpool"),
    ("circle-internet-group-ondo-tokenized-stock", "CRCLON", "Circle Internet Group (Ondo Tokenized Stock)"),
    ("circle-xstock", "CRCLX", "Circle xStock"),
    ("cross-2", "CROSS", "CROSS"),
    ("crvusd", "CRVUSD", "crvUSD"),
    ("casper-network", "CSPR", "Casper Network"),
    ("certik", "CTK", "Shentu"),
    ("cartesi", "CTSI", "Cartesi"),
    ("cap-usd", "CUSD", "Cap USD"),
    ("compounding-open-dollar", "CUSDO", "Compounding OpenDollar"),
    ("civic", "CVC", "Civic"),
    ("commonwealth-2", "CWU", "CommonWealth"),
    ("cargox", "CXO", "CargoX"),
    ("cyberconnect", "CYBER", "CYBER"),
    ("cysic", "CYS", "Cysic"),
    ("constellation-labs", "DAG", "Constellation"),
    ("debridge", "DBR", "deBridge"),
    ("degen-base", "DEGEN", "Degen"),
    ("deapcoin", "DEP", "DEAPCOIN"),
    ("deso", "DESO", "Decentralized Social"),
    ("degate", "DG", "DeGate"),
    ("digibyte", "DGB", "DigiByte"),
    ("dia-data", "DIA", "DIA"),
    ("diem", "DIEM", "Diem"),
    ("dkargo", "DKA", "dKargo"),
    ("dodo", "DODO", "DODO"),
    ("dogs-2", "DOGS", "Dogs"),
    ("dola-usd", "DOLA", "DOLA"),
    ("dolomite", "DOLO", "Dolomite"),
    ("doodles", "DOOD", "Doodles"),
    ("dora-2", "DORA", "DORA"),
    ("dovu-2", "DOVU", "DOVU"),
    ("drift-protocol", "DRIFT", "Drift Protocol"),
    ("derive", "DRV", "Derive"),
    ("dual", "DUAL", "Dual"),
    ("standx-dusd", "DUSD", "StandX DUSD"),
    ("dusk-network", "DUSK", "DUSK"),
    ("dacxi", "DXI", "Dacxi"),
    ("lido-earn-eth", "EARNETH", "Lido Earn ETH"),
    ("ebtc-2", "EBTC", "eBTC"),
    ("edgex", "EDGE", "edgeX"),
    ("edu-coin", "EDU", "Open Campus"),
    ("egl1", "EGL1", "EGL1"),
    ("eitherway", "EITHER", "Eitherway"),
    ("elephant-money", "ELEPHANT", "Elephant Money"),
    ("aelf", "ELF", "aelf"),
    ("escoin-token", "ELG", "Escoin"),
    ("dogelon-mars", "ELON", "Dogelon Mars"),
    ("elsa", "ELSA", "Elsa"),
    ("enjincoin", "ENJ", "Enjin Coin"),
    ("enso", "ENSO", "Enso"),
    ("caldera", "ERA", "Caldera"),
    ("ergo", "ERG", "Ergo"),
    ("eclipse-3", "ES", "Eclipse"),
    ("espresso", "ESP", "Espresso"),
    ("ethereum-pow-iou", "ETHW", "EthereumPoW"),
    ("electroneum", "ETN", "Electroneum"),
    ("euler", "EUL", "Euler"),
    ("societe-generale-forge-eurcv", "EURCV", "EUR CoinVertible"),
    ("monerium-eur-money-2", "EURE", "Monerium EUR emoney"),
    ("eurite", "EURI", "Eurite"),
    ("stasis-eurs", "EURS", "STASIS EURO"),
    ("spiko-amundi-overnight-swap-fund-eur", "EURSAFO", "Spiko Amundi Overnight Swap Fund (EUR)"),
    ("spiko-digital-assets-cash-carry-fund-euro-share-class", "EURSPKCC", "Spiko Digital Assets Cash & Carry Fund - Euro Share Class"),
    ("electronic-usd", "EUSD", "Electronic USD"),
    ("eutbl", "EUTBL", "Spiko EU T-Bills Money Market Fund"),
    ("everything", "EV", "Everything"),
    ("energy-web-token", "EWT", "Energy Web Token"),
    ("exod", "EXOD", "EXOD"),
    ("synfutures", "F", "SynFutures"),
    ("freysa-ai", "FAI", "Freysa AI"),
    ("fractal-bitcoin", "FB", "Fractal Bitcoin"),
    ("fidelity-digital-interest-token", "FDIT", "Fidelity Digital Interest Token"),
    ("felix-feusd", "FEUSD", "Felix feUSD"),
    ("falcon-finance-ff", "FF", "Falcon Finance"),
    ("bonfida", "FIDA", "Bonfida"),
    ("fidelity-digital-dollar", "FIDD", "Fidelity Digital Dollar"),
    ("figure-heloc", "FIGR_HELOC", "Figure Heloc"),
    ("zcoin", "FIRO", "Firo"),
    ("sygnum-fiusd-liquidity-fund", "FIUSD", "Sygnum FIUSD Liquidity Fund"),
    ("chainflip", "FLIP", "Chainflip"),
    ("flock-2", "FLOCK", "FLOCK"),
    ("instadapp", "FLUID", "Fluid"),
    ("zelcash", "FLUX", "Flux"),
    ("official-fo", "FO", "Official FO"),
    ("fogo", "FOGO", "Fogo"),
    ("folks", "FOLKS", "FOLKS"),
    ("just-a-frog", "FROG", "just a frog"),
    ("frax-usd", "FRXUSD", "Frax USD"),
    ("flying-tulip", "FT", "Flying Tulip"),
    ("faith-tribe", "FTRB", "Faith Tribe"),
    ("fulcrom", "FUL", "Fulcrom"),
    ("fx-usd-saving", "FXSAVE", "f(x) USD Saving"),
    ("f-x-protocol-fxusd", "FXUSD", "f(x) Protocol fxUSD"),
    ("g-token", "G", "Gravity (by Galxe)"),
    ("project-galaxy", "GAL", "GAL (migrated to Gravity - G)"),
    ("gama-token", "GAMA", "Gama Token"),
    ("gamebuild", "GAME", "GameBuild"),
    ("global-commercial-business", "GCB", "Global Commercial Business"),
    ("playnance", "GCOIN", "Playnance"),
    ("gekko", "GEKKO", "GEKKO"),
    ("genius-3", "GENIUS", "Genius"),
    ("geodnet", "GEOD", "Geodnet"),
    ("geode-chain", "GEODE", "Geode Chain"),
    ("goldfish-gold", "GGBR", "Goldfish Gold"),
    ("gho", "GHO", "GHO"),
    ("gigachad-2", "GIGA", "Gigachad"),
    ("giggle-fund", "GIGGLE", "Giggle Fund"),
    ("glidr", "GLIDR", "Glidr"),
    ("stepn", "GMT", "GMT"),
    ("gmx", "GMX", "GMX"),
    ("goatseus-maximus", "GOAT", "Goatseus Maximus"),
    ("gohome", "GOHOME", "GOHOME"),
    ("gmt-token", "GOMINING", "GoMining Token"),
    ("alphabet-class-a-ondo-tokenized-stock", "GOOGLON", "Alphabet Class A (Ondo Tokenized Stock)"),
    ("alphabet-xstock", "GOOGLX", "Alphabet xStock"),
    ("goplus-security", "GPS", "GoPlus Security"),
    ("gold-park", "GPT", "Gold Park"),
    ("grass", "GRASS", "Grass"),
    ("grx-chain", "GRX", "GRX Chain"),
    ("superfortune", "GUA", "Superfortune"),
    ("gunz", "GUN", "Gunz"),
    ("gusd", "GUSD", "GUSD"),
    ("ethgas-2", "GWEI", "ETHGas"),
    ("gxchain", "GXC", "GXChain"),
    ("humanity", "H", "Humanity"),
    ("h2o-2", "H2O", "H2O"),
    ("handy", "HANDY", "Handy"),
    ("hash-2", "HASH", "Provenance Blockchain"),
    ("hive_dollar", "HBD", "Hive Dollar"),
    ("hydradx", "HDX", "Hydration"),
    ("hegic", "HEGIC", "Hegic"),
    ("hermez-network-token", "HEZ", "Hermez Network"),
    ("hive", "HIVE", "Hive"),
    ("holoworld", "HOLO", "Holoworld"),
    ("home", "HOME", "HOME"),
    ("honey-3", "HONEY", "Honey"),
    ("holotoken", "HOT", "Holo"),
    ("hippo-protocol", "HP", "Hippo Protocol"),
    ("hashkey-ecopoints", "HSK", "HashKey Platform Token"),
    ("htx-dao", "HTX", "HTX DAO"),
    ("huma-finance", "HUMA", "Huma Finance"),
    ("hundred", "HUNDRED", "HUNDRED"),
    ("hunt-token", "HUNT", "Hunt"),
    ("hyperlane", "HYPER", "Hyperlane"),
    ("ishares-bitcoin-trust-ondo-tokenized", "IBITON", "iShares Bitcoin Trust (Ondo Tokenized)"),
    ("ibs-3", "IBS", "IBS"),
    ("impossible-cloud-network-token", "ICNT", "Impossible Cloud Network Token"),
    ("icon", "ICX", "ICON"),
    ("meet48", "IDOL", "MEET48"),
    ("ishares-core-msci-eafe-etf-ondo-tokenized-etf", "IEFAON", "iShares Core MSCI EAFE ETF (Ondo Tokenized ETF)"),
    ("illuvium", "ILV", "Illuvium"),
    ("infinit", "IN", "INFINIT"),
    ("incrypt", "INC", "Incrypt"),
    ("initia", "INIT", "Initia"),
    ("intel-ondo-tokenized-stock", "INTCON", "Intel (Ondo Tokenized Stock)"),
    ("infinex-2", "INX", "Infinex"),
    ("io", "IO", "io.net"),
    ("iostoken", "IOST", "IOST"),
    ("everipedia", "IQ", "IQ"),
    ("irys", "IRYS", "Irys"),
    ("islamic-coin", "ISLM", "Islamic Coin"),
    ("infinifi-usd", "IUSD", "InfiniFi USD"),
    ("ishares-core-s-p-500-etf-ondo-tokenized-etf", "IVVON", "iShares Core S&P 500 ETF (Ondo Tokenized ETF)"),
    ("janus-henderson-anemoy-aaa-clo-fund", "JAAA", "Janus Henderson Anemoy AAA CLO Fund"),
    ("janction", "JCT", "Janction"),
    ("jelly-my-jelly", "JELLYJELLY", "Jelly-My-Jelly"),
    ("joe", "JOE", "JOE"),
    ("jpycoin", "JPYC", "JPY Coin"),
    ("janus-henderson-anemoy-treasury-fund", "JTRSY", "Janus Henderson Anemoy Treasury Fund"),
    ("jupusd", "JUPUSD", "JupUSD"),
    ("jusd", "JUSD", "JUSD"),
    ("kinesis-silver", "KAG", "Kinesis Silver"),
    ("kaio", "KAIO", "KAIO"),
    ("katana-network-token", "KAT", "Katana"),
    ("kinesis-gold", "KAU", "Kinesis Gold"),
    ("kernel-2", "KERNEL", "KernelDAO"),
    ("kgen", "KGEN", "KGeN"),
    ("kishu-inu", "KISHU", "Kishu Inu"),
    ("kite-2", "KITE", "Kite"),
    ("kamino", "KMNO", "Kamino"),
    ("kyber-network-crystal", "KNC", "Kyber Network Crystal"),
    ("kinetiq", "KNTQ", "Kinetiq"),
    ("bnb48-club-token", "KOGE", "KOGE"),
    ("keeta", "KTA", "Keeta"),
    ("bitkub-coin", "KUB", "KUB Coin"),
    ("lagrange", "LA", "Lagrange"),
    ("lab", "LAB", "LAB"),
    ("solayer", "LAYER", "Solayer"),
    ("lovebit", "LB", "LoveBit"),
    ("law-blocks", "LBT", "Law Blocks AI"),
    ("lcx", "LCX", "LCX"),
    ("ethlend", "LEND", "Aave [OLD]"),
    ("linea", "LINEA", "Linea"),
    ("loaded-lions", "LION", "Loaded Lions"),
    ("lista", "LISTA", "Lista DAO"),
    ("helio-protocol-hay", "LISUSD", "Lista USD"),
    ("lighter", "LIT", "Lighter"),
    ("infinifi-locked-iusd-1week", "LIUSD", "infiniFi Locked iUSD (1week)"),
    ("tokenlon", "LON", "Tokenlon"),
    ("liquity", "LQTY", "Liquity"),
    ("loopring", "LRC", "Loopring"),
    ("lisk", "LSK", "Lisk"),
    ("terra-luna-2", "LUNA", "Terra"),
    ("liquity-usd", "LUSD", "Liquity USD"),
    ("mag7-ssi", "MAG7.SSI", "MAG7.ssi"),
    ("magic", "MAGIC", "Treasure"),
    ("magma-finance", "MAGMA", "Magma Finance"),
    ("manifesting", "MANIFEST", "Manifesting"),
    ("manta-network", "MANTA", "Manta Network"),
    ("mantra", "MANTRA", "MANTRA"),
    ("marsmi", "MARSMI", "MarsMi"),
    ("mask-network", "MASK", "Mask Network"),
    ("max-token", "MAX", "MAX"),
    ("mbg-by-multibank-group", "MBG", "MBG By Multibank Group"),
    ("moviebloc", "MBL", "MovieBloc"),
    ("magic-eden", "ME", "Magic Eden"),
    ("medibloc", "MED", "Medibloc"),
    ("megaeth", "MEGA", "MegaETH"),
    ("melania-meme", "MELANIA", "Melania Meme"),
    ("memecoin-2", "MEME", "Memecoin"),
    ("merlin-chain", "MERL", "Merlin Chain"),
    ("meteora", "MET", "Meteora"),
    ("meta-2-2", "META", "MetaDAO"),
    ("metal-blockchain", "METAL", "Metal Blockchain"),
    ("metis-token", "METIS", "Metis"),
    ("midas-mf-one", "MF-ONE", "Midas mF-ONE"),
    ("midas-fasanara-global", "MGLOBAL", "Midas Fasanara Global"),
    ("mango-network", "MGO", "Mango Network"),
    ("meme-horse", "MHORSE", "MEME HORSE"),
    ("midas-mhyper", "MHYPER", "Midas mHYPER"),
    ("mira-3", "MIRA", "Mira"),
    ("milk-alliance", "MLK", "MiL.k"),
    ("momentum-3", "MMT", "Momentum"),
    ("metamui", "MMUI", "MetaMUI"),
    ("mango-markets", "MNGO", "Mango"),
    ("monad", "MON", "Monad"),
    ("monji", "MONJI", "monji"),
    ("moo-deng", "MOODENG", "Moo Deng"),
    ("morpheusai", "MOR", "Morpheus AI"),
    ("moonriver", "MOVR", "Moonriver"),
    ("my-paqman-coin", "MPC", "My Paqman Coin"),
    ("microsoft-ondo-tokenized-stock", "MSFTON", "Microsoft (Ondo Tokenized Stock)"),
    ("microstrategy-xstock", "MSTRX", "MicroStrategy xStock"),
    ("main-street-usd", "MSUSD", "Main Street USD"),
    ("main-street-yield", "MSY", "Main Street Yield"),
    ("midas-mtbill", "MTBILL", "Midas mTBILL"),
    ("metal", "MTL", "Metal DAO"),
    ("micron-technology-ondo-tokenized-stock", "MUON", "Micron Technology (Ondo Tokenized Stock)"),
    ("metamask-usd", "MUSD", "MetaMask USD"),
    ("mustang", "MUST", "Mustang"),
    ("mass-vehicle-ledger", "MVL", "MVL"),
    ("mimblewimblecoin", "MWC", "MimbleWimbleCoin"),
    ("memetern", "MXT", "Memetern"),
    ("myx-finance", "MYX", "MYX Finance"),
    ("naoris", "NAORIS", "Naoris Protocol"),
    ("dmt-nat", "NAT", "DMT-NAT"),
    ("nest-basis-vault", "NBASIS", "Nest Basis Vault"),
    ("novachargex-coin", "NCX", "NovaChargeX Coin"),
    ("neet", "NEET", "Not in Employment, Education, or Training"),
    ("neiro-3", "NEIRO", "Neiro"),
    ("newton-protocol", "NEWT", "Newton Protocol"),
    ("nexus-4", "NEX", "Nexus"),
    ("midnight-3", "NIGHT", "Midnight"),
    ("nillion", "NIL", "Nillion"),
    ("mindwavedao", "NILA", "MindWaveDAO"),
    ("nkyc-token", "NKYC", "NKYC Token"),
    ("numeraire", "NMR", "Numeraire"),
    ("nockchain", "NOCK", "Nockchain"),
    ("nosana", "NOS", "Nosana"),
    ("notcoin", "NOT", "Notcoin"),
    ("changenow", "NOW", "ChangeNOW"),
    ("non-playable-coin", "NPC", "Non-Playable Coin"),
    ("nusd-2", "NUSD", "Neutrl USD"),
    ("nvidia-ondo-tokenized-stock", "NVDAON", "NVIDIA (Ondo Tokenized Stock)"),
    ("nvidia-xstock", "NVDAX", "NVIDIA xStock"),
    ("nxm", "NXM", "Nexus Mutual"),
    ("nexpace", "NXPC", "Nexpace"),
    ("nexst", "NXT", "NEXST"),
    ("nxusd", "NXUSD", "NXUSD"),
    ("nyc-token", "NYC", "NYC"),
    ("nym", "NYM", "Nym"),
    ("ocean-protocol", "OCEAN", "Ocean Protocol"),
    ("octra", "OCT", "Octra"),
    ("onfa", "OFT", "ONFA"),
    ("olympus", "OHM", "Olympus"),
    ("oho-blockchain", "OHO", "OHO Blockchain"),
    ("ecomi", "OMI", "ECOMI"),
    ("orochi-network", "ON", "Orochi Network"),
    ("harmony", "ONE", "Harmony"),
    ("ong", "ONG", "Ontology Gas"),
    ("ontology", "ONT", "Ontology"),
    ("onyc", "ONYC", "OnRe Tokenized Reinsurance"),
    ("openledger-2", "OPEN", "OpenLedger"),
    ("opengradient", "OPG", "OpenGradient"),
    ("opinion", "OPN", "Opinion"),
    ("orbs", "ORBS", "Orbs"),
    ("orca", "ORCA", "Orca"),
    ("orderly-network", "ORDER", "Orderly"),
    ("ordinals", "ORDI", "ORDI"),
    ("ore", "ORE", "ORE"),
    ("orizon", "ORI", "Orizon"),
    ("osaka-protocol", "OSAK", "Osaka Protocol"),
    ("osmosis", "OSMO", "Osmosis"),
    ("ousg", "OUSG", "OUSG"),
    ("ozapay", "OZA", "Ozapay"),
    ("ozone-chain", "OZO", "Ozone Chain"),
    ("tradable-na-third-party-online-merchant-sstn", "PC0000015", "Tradable NA Third Party Online Merchant SSTN"),
    ("tradable-north-america-pos-lender-sstn", "PC0000019", "Tradable North America PoS Lender SSTN"),
    ("tradable-singapore-fintech-ssl-2", "PC0000023", "Tradable Singapore Fintech SSL"),
    ("tradable-latam-bnpl-sstn", "PC0000027", "Tradable LatAm BNPL SSTN"),
    ("tradable-na-rent-financing-platform-sstn", "PC0000031", "Tradable NA Rent Financing Platform SSTN"),
    ("tradable-apac-diversified-finance-provider-sstn", "PC0000033", "Tradable APAC Diversified Finance Provider SSTN"),
    ("tradable-eu-latam-pos-financing-sstl", "PC0000049", "Tradable Eu/LatAm PoS Financing SSTL"),
    ("tradable-singapore-fintech-ssl", "PC0000077", "Tradable Singapore Fintech SSL"),
    ("tradable-na-legal-receivables-ssl", "PC0000081", "Tradable NA Legal Receivables SSL"),
    ("tradable-latam-middle-market-lender-sstl", "PC0000085", "Tradable LatAm Middle-Market Lender SSTL"),
    ("latam-residential-sstl", "PC0000089", "Tradable LatAm Residential SSTL"),
    ("tradable-latam-fintech-sstn", "PC0000097", "Tradable LatAm Fintech SSTN"),
    ("na-post-settlement-legal-financing-receivables", "PC0000101", "Tradable NA Post-Settlement Legal Financing Receivables"),
    ("na-capital-as-a-service-sstn", "PC0016245", "NA Capital-as-a-Service SSTN"),
    ("pay-coin", "PCI", "Paycoin"),
    ("peaq-2", "PEAQ", "peaq"),
    ("constitutiondao", "PEOPLE", "ConstitutionDAO"),
    ("pleasing-gold", "PGOLD", "Pleasing Gold"),
    ("pha", "PHA", "PHALA"),
    ("pieverse", "PIEVERSE", "Pieverse"),
    ("pinksale", "PINKSALE", "PinkSale"),
    ("pippin", "PIPPIN", "pippin"),
    ("playsout", "PLAY", "PlaysOut"),
    ("palladium-network", "PLLD", "Palladium Network"),
    ("pumpmeme", "PM", "PumpMeme"),
    ("precious-metals-usd", "PMUSD", "Precious Metals USD"),
    ("pocket-network", "POKT", "Pocket Network"),
    ("polymesh", "POLYX", "Polymesh"),
    ("marlin", "POND", "Marlin"),
    ("ponke", "PONKE", "PONKE"),
    ("power-protocol", "POWER", "Power Protocol"),
    ("power-ledger", "POWR", "Powerledger"),
    ("predictions", "PRDT", "Predictions"),
    ("spacex-republic-pre-ipo", "PRESPAX", "SpaceX (Republic Pre-IPO)"),
    ("hastra-prime", "PRIME", "PRIME"),
    ("prize-protocol", "PRIZE", "Prize Protocol"),
    ("perle", "PRL", "Perle"),
    ("propy", "PRO", "Propy"),
    ("prometeus", "PROM", "Prom"),
    ("pharos-network", "PROS", "Pharos"),
    ("paris-saint-germain-fan-token", "PSG", "Paris Saint-Germain Fan Token"),
    ("the-grays-currency", "PTGC", "The Grays Currency"),
    ("puff-the-dragon", "PUFF", "Puff The Dragon"),
    ("pumpcade", "PUMPCADE", "PUMPCADE"),
    ("pundi-x-2", "PUNDIX", "Pundi X"),
    ("purr-2", "PURR", "Purr"),
    ("capybobo", "PYBOBO", "Capybobo"),
    ("pythia", "PYTHIA", "PYTHIA"),
    ("quack-ai", "Q", "Quack AI"),
    ("qanplatform", "QANX", "QANplatform"),
    ("quantixai", "QFI", "Quantix Finance"),
    ("qie", "QIE", "QIE Blockchain"),
    ("qkacoin", "QKA", "Qkacoin"),
    ("quark-chain", "QKC", "QuarkChain"),
    ("invesco-qqq-etf-ondo-tokenized-etf", "QQQON", "Invesco QQQ ETF (Ondo Tokenized ETF)"),
    ("nasdaq-xstock", "QQQX", "Nasdaq xStock"),
    ("quantum-resistant-ledger", "QRL", "Quantum Resistant Ledger"),
    ("quai-network", "QUAI", "Quai Network"),
    ("qubic-network", "QUBIC", "Qubic"),
    ("railgun", "RAIL", "Railgun"),
    ("rain", "RAIN", "Rain"),
    ("ravedao", "RAVE", "RaveDAO"),
    ("ready", "READY", "Ready Cards"),
    ("reallink", "REAL", "RealLink"),
    ("redstone-oracles", "RED", "RedStone"),
    ("unit-00-rei", "REI", "Rei"),
    ("rekt-4", "REKT", "Rekt"),
    ("request-network", "REQ", "Request"),
    ("royal-euro", "REUR", "Royal Euro"),
    ("re-protocol-reusd", "REUSD", "Re Protocol reUSD"),
    ("re-protocol-reusde", "REUSDE", "Re Protocol reUSDe"),
    ("renzo", "REZ", "Renzo"),
    ("rif-token", "RIF", "Rootstock Infrastructure Framework"),
    ("riv-coin", "RIV", "RIV Coin"),
    ("river", "RIVER", "River"),
    ("rollbit-coin", "RLB", "Rollbit Coin"),
    ("iexec-rlc", "RLC", "iExec RLC"),
    ("reental", "RNT", "Reental"),
    ("robo-token-2", "ROBO", "Fabric Protocol"),
    ("rosa-inu", "ROSA", "Rosa Inu"),
    ("oasis-network", "ROSE", "Oasis"),
    ("rocket-pool", "RPL", "Rocket Pool"),
    ("researchcoin", "RSC", "ResearchCoin"),
    ("rujira", "RUJI", "Rujira"),
    ("royal-dollar", "RUSD", "Royal Dollar"),
    ("ravencoin", "RVN", "Ravencoin"),
    ("ryze", "RYZE", "Ryze"),
    ("safo", "SAFO", "Spiko Amundi Overnight Swap Fund"),
    ("sahara-ai", "SAHARA", "Sahara AI"),
    ("sai", "SAI", "Sai"),
    ("sailout-royalty", "SAIL.R", "SailOut Royalty"),
    ("sapien-2", "SAPIEN", "Sapien"),
    ("sats-ordinals", "SATS", "SATS (Ordinals)"),
    ("satoshi-stablecoin", "SATUSD", "Satoshi Stablecoin"),
    ("saucerswap", "SAUCE", "SaucerSwap"),
    ("snowbank", "SB", "Snowbank"),
    ("siacoin", "SC", "Siacoin"),
    ("secret", "SCRT", "Secret"),
    ("seda-2", "SEDA", "SEDA"),
    ("sentient", "SENT", "Sentient"),
    ("sentismai", "SENTIS", "SentismAI"),
    ("openserv", "SERV", "OpenServ"),
    ("staked-frax-usd", "SFRXUSD", "Frax Staked frxUSD"),
    ("songbird", "SGB", "Songbird"),
    ("shuffle-2", "SHFL", "Shuffle"),
    ("show-2", "SHOW", "SHOW"),
    ("stronghold-token", "SHX", "Stronghold"),
    ("sierra-2", "SIERRA", "Sierra"),
    ("sign-global", "SIGN", "Sign"),
    ("singularry", "SINGULARRY", "Singularry"),
    ("siren-2", "SIREN", "Siren"),
    ("seeker", "SKR", "Seeker"),
    ("skyai", "SKYAI", "SkyAI"),
    ("smooth-love-potion", "SLP", "Smooth Love Potion"),
    ("ishares-silver-trust-ondo-tokenized-stock", "SLVON", "iShares Silver Trust (Ondo Tokenized Stock)"),
    ("solstice", "SLX", "Solstice"),
    ("affine", "SN120", "affine"),
    ("taohash", "SN14", "Cacheon"),
    ("templar", "SN3", "τemplar"),
    ("bitmind", "SN34", "BitMind"),
    ("targon", "SN4", "Targon"),
    ("score", "SN44", "Score"),
    ("openkaito", "SN5", "OpenKaito"),
    ("celium", "SN51", "lium"),
    ("gradients", "SN56", "Gradients"),
    ("ridges-ai", "SN62", "Ridges AI"),
    ("chutes", "SN64", "Chutes"),
    ("nova-3", "SN68", "NOVA"),
    ("hippius", "SN75", "Hippius"),
    ("proprietary-trading-network", "SN8", "Proprietary Trading Network"),
    ("iota-2", "SN9", "iota"),
    ("sandisk-ondo-tokenized", "SNDKON", "SanDisk (Ondo Tokenized)"),
    ("status", "SNT", "Status"),
    ("sodax", "SODA", "SODAX"),
    ("somnia", "SOMI", "Somnia"),
    ("soon-2", "SOON", "SOON"),
    ("sophon", "SOPH", "Sophon"),
    ("strategic-oil-supply-2", "SOS", "Strategic Oil Supply"),
    ("sosovalue", "SOSO", "SoSoValue"),
    ("spacecoin-2", "SPACE", "Spacecoin"),
    ("spell-token", "SPELL", "Spell"),
    ("spark-2", "SPK", "Spark"),
    ("spdr-s-p-500-etf-ondo-tokenized-etf", "SPYON", "SPDR S&P 500 ETF (Ondo Tokenized ETF)"),
    ("sp500-xstock", "SPYX", "SP500 xStock"),
    ("subsquid", "SQD", "SQD"),
    ("storx", "SRX", "StorX"),
    ("ssv-network", "SSV", "SSV Network"),
    ("small-thing", "ST", "Small Thing"),
    ("stable-2", "STABLE", "​​Stable"),
    ("securitize-tokenized-aaa-clo-fund", "STAC", "Securitize Tokenized AAA CLO Fund"),
    ("starpower", "STAR", "Starpower"),
    ("stau", "STAU", "STAU"),
    ("stbl", "STBL", "STBL"),
    ("steem", "STEEM", "Steem"),
    ("stargate-finance", "STG", "Stargate Finance"),
    ("striker", "STKRI", "Striker"),
    ("ston-2", "STON", "STON"),
    ("stratis", "STRAX", "Xertra"),
    ("strategy-pp-variable-xstock", "STRCX", "Strategy PP Variable xStock"),
    ("strike-2", "STRIKE", "Strike"),
    ("strikecoin", "STRX", "StrikeX"),
    ("nusd", "SUSD", "Synthetix sUSD"),
    ("swftcoin", "SWFTC", "SWFTCOIN"),
    ("swop-2", "SWOP", "Swop"),
    ("space-and-time", "SXT", "Space and Time"),
    ("threshold-network-token", "T", "Threshold Network"),
    ("tac", "TAC", "TAC"),
    ("tagger", "TAG", "TAGGER"),
    ("taiko", "TAIKO", "Taiko"),
    ("tronbank", "TBK", "TronBank"),
    ("tcy", "TCY", "THORChain Yield"),
    ("tdccp", "TDCCP", "TDCCP"),
    ("telcoin", "TEL", "Telcoin"),
    ("temple", "TEMPLE", "TempleDAO"),
    ("tokenised-gbp", "TGBP", "Tokenised GBP"),
    ("theo-short-duration-us-treasury-fund", "THBILL", "Theo Short Duration US Treasury Fund"),
    ("ribbita-by-virtuals", "TIBBIR", "Ribbita by Virtuals"),
    ("the-innovation-game", "TIG", "The Innovation Game"),
    ("tokenize-xchange", "TKX", "Tokenize Xchange"),
    ("ishares-20-year-treasury-bond-etf-ondo-tokenized-etf", "TLTON", "iShares 20+ Year Treasury Bond ETF (Ondo Tokenized ETF)"),
    ("tornado-cash", "TORN", "Tornado Cash"),
    ("triple-plus", "TPT", "Triple Plus"),
    ("origintrail", "TRAC", "OriginTrail"),
    ("tellor", "TRB", "Tellor Tributes"),
    ("tree-capital", "TREE", "Tree"),
    ("tria", "TRIA", "TRIA"),
    ("trillions", "TRILLIONS", "Trillions"),
    ("troll-2", "TROLL", "TROLL"),
    ("swarm-network", "TRUTH", "Swarm Network"),
    ("tesla-ondo-tokenized-stock", "TSLAON", "Tesla (Ondo Tokenized Stock)"),
    ("tesla-xstock", "TSLAX", "Tesla xStock"),
    ("test-3", "TST", "Test"),
    ("tx", "TX", "tx"),
    ("united-stables", "U", "United Stables"),
    ("unifai-network", "UAI", "UnifAI Network"),
    ("unibase", "UB", "Unibase"),
    ("uchain-2", "UCN", "UCHAIN"),
    ("spiko-uk-t-bills-money-market-fund", "UKTBL", "Spiko UK T-Bills Money Market Fund"),
    ("ultima", "ULTIMA", "Ultima"),
    ("uma", "UMA", "UMA"),
    ("manadia", "UMXM", "Manadia"),
    ("unipoly", "UNP", "Unipoly"),
    ("unitywallet-token", "UNT", "UnityWallet Token"),
    ("unitas", "UP", "Unitas"),
    ("unit-pump", "UPUMP", "Unit Pump"),
    ("uquid-coin", "UQC", "Uquid Coin"),
    ("usa", "USAT", "USAT"),
    ("usual-usd", "USD0", "Usual USD"),
    ("usda-2", "USDA", "USDa"),
    ("usdai", "USDAI", "USDai"),
    ("saturn-dollar", "USDAT", "Saturn Dollar"),
    ("falcon-finance", "USDF", "Falcon USD"),
    ("global-dollar", "USDG", "Global Dollar"),
    ("usdgo", "USDGO", "USDGO"),
    ("usdh-2", "USDH", "USDH"),
    ("usdkg", "USDKG", "USDKG"),
    ("megausd", "USDM", "MegaUSD"),
    ("openeden-open-dollar", "USDO", "OpenEden OpenDollar"),
    ("ondo-u-s-dollar-token", "USDON", "Ondo U.S. Dollar Token"),
    ("paxos-standard", "USDP", "Pax Dollar"),
    ("stablr-usd", "USDR", "StablR USD"),
    ("usds", "USDS", "USDS"),
    ("usdtb", "USDTB", "USDtb"),
    ("usdu", "USDU", "USDu"),
    ("usdx", "USDX", "USDX"),
    ("ondo-us-dollar-yield", "USDY", "Ondo US Dollar Yield"),
    ("noon-usn", "USN", "Noon USN"),
    ("usp-yield-optimized-stablecoin", "USP", "USP Yield Optimized Stablecoin"),
    ("superstate-short-duration-us-government-securities-fund-ustb", "USTB", "Superstate Short Duration U.S. Government Securities Fund (USTB)"),
    ("spiko-us-t-bills-money-market-fund", "USTBL", "Spiko US T-Bills Money Market Fund"),
    ("terrausd", "USTC", "TerraClassicUSD"),
    ("usual", "USUAL", "Usual"),
    ("usx", "USX", "USX"),
    ("hashnote-usyc", "USYC", "Circle USYC"),
    ("unity-2", "UTY", "Unity"),
    ("utya", "UTYA", "Utya"),
    ("unity-usd", "UUSD", "Unity USD"),
    ("unit-plasma", "UXPL", "Unit Plasma"),
    ("vana", "VANA", "Vana"),
    ("vaneck-treasury-fund", "VBILL", "VanEck Treasury Fund"),
    ("vicicoin", "VCNT", "ViciCoin"),
    ("blockv", "VEE", "BLOCKv"),
    ("velvet", "VELVET", "Velvet"),
    ("venom", "VENOM", "Venom"),
    ("vine", "VINE", "Vine"),
    ("victoria-vr", "VR", "Victoria VR"),
    ("verus-coin", "VRSC", "Verus"),
    ("vision-3", "VSN", "Vision"),
    ("vethor-token", "VTHO", "VeThor"),
    ("vultisig", "VULT", "Vultisig"),
    ("vvs-finance", "VVS", "VVS Finance"),
    ("venice-token", "VVV", "Venice Token"),
    ("waves", "WAVES", "Waves"),
    ("wax", "WAXP", "WAX"),
    ("whitebit", "WBT", "WhiteBIT Coin"),
    ("moonwell-artemis", "WELL", "Moonwell"),
    ("humidifi", "WET", "HumidiFi"),
    ("wefi", "WFI", "WeFi"),
    ("whiteheart", "WHITE", "Whiteheart"),
    ("wink", "WIN", "WINkLink"),
    ("wiki-cat", "WKC", "Wiki Cat"),
    ("world-liberty-financial", "WLFI", "World Liberty Financial"),
    ("world-mobile-token", "WMTX", "World Mobile Token"),
    ("wojak-5", "WOJAK", "wojak"),
    ("woo-network", "WOO", "WOO"),
    ("would", "WOULD", "would"),
    ("xai-blockchain", "XAI", "Xai"),
    ("anoma", "XAN", "Anoma"),
    ("matrixdock-gold", "XAUM", "Matrixdock Gold"),
    ("chia", "XCH", "Chia"),
    ("xdai", "XDAI", "XDAI"),
    ("x-dol-x", "XDOL", "x-DOL-x"),
    ("nano", "XNO", "Nano"),
    ("codatta", "XNY", "Codatta"),
    ("xphere", "XP", "Xphere"),
    ("xpin-network", "XPIN", "XPIN Network"),
    ("plasma", "XPL", "Plasma"),
    ("proton", "XPR", "XPR Network"),
    ("radix", "XRD", "Radix"),
    ("xtcom-token", "XT", "XT.com"),
    ("xtusd", "XTUSD", "XT Stablecoin XTUSD"),
    ("straitsx-xusd", "XUSD", "StraitsX XUSD"),
    ("verge", "XVG", "Verge"),
    ("venus", "XVS", "Venus"),
    ("xyo-network", "XYO", "XYO Network"),
    ("yield-basis", "YB", "Yield Basis"),
    ("yearn-finance", "YFI", "yearn.finance"),
    ("yield-guild-games", "YGG", "Yield Guild Games"),
    ("ylds", "YLDS", "YLDS"),
    ("aegis-yusd", "YUSD", "Aegis YUSD"),
    ("zama", "ZAMA", "Zama"),
    ("zano", "ZANO", "Zano"),
    ("zerobase", "ZBT", "ZEROBASE"),
    ("frankencoin", "ZCHF", "Frankencoin"),
    ("zencash", "ZEN", "Horizen"),
    ("zentry", "ZENT", "Zentry"),
    ("zerebro", "ZEREBRO", "Zerebro"),
    ("zest-protocol", "ZEST", "Zest Protocol"),
    ("zetachain", "ZETA", "ZetaChain"),
    ("zignaly", "ZIG", "ZIGChain"),
    ("boundless", "ZKC", "Boundless"),
    ("0x", "ZRX", "0x Protocol"),
    ("jixiangma", "吉祥马", "吉祥马"),
    ("hakimi", "哈基米", "哈基米 (Hajimi)"),
    ("bianrensheng", "币安人生", "币安人生 (BinanceLife)")
)